// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRPP-x_swA-qBmQekhu9Vnf2U0-XztMk4',
    appId: '1:184694825211:web:56fda46c06fa559aae505e',
    messagingSenderId: '184694825211',
    projectId: 'ecommerce-9a3ee',
    authDomain: 'ecommerce-9a3ee.firebaseapp.com',
    storageBucket: 'ecommerce-9a3ee.appspot.com',
    measurementId: 'G-HZ3Q915XHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsiu7vx7UWR-SkDL-vOwLJDmpPA8xMAPg',
    appId: '1:184694825211:android:e0fe3577bf6e66e6ae505e',
    messagingSenderId: '184694825211',
    projectId: 'ecommerce-9a3ee',
    storageBucket: 'ecommerce-9a3ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIJGL5joAv-fXq7_Y_6HbKgHPMXyBM4Y',
    appId: '1:184694825211:ios:a6e2e4602f8502f8ae505e',
    messagingSenderId: '184694825211',
    projectId: 'ecommerce-9a3ee',
    storageBucket: 'ecommerce-9a3ee.appspot.com',
    androidClientId: '184694825211-n3d36i9dv7nuqa0ubd2caeo0mqkputqk.apps.googleusercontent.com',
    iosClientId: '184694825211-kqaj3orgep1279qnh9iquq31kpdiad9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.nsbmStore',
  );
}
